### ISSUE TITLE
Falsche Darstellung von Rechnungsdatums bei vorausgegangenen Rechnungen

### ISSUE THREAD

**Issue by hiwilfried** [jcthiele/OpenXRechnungToolbox#1]
Obwohl in der zugrundeliegenden XML-Datei im selben Format angegeben wie der Abrechnungszeitraum, werden die Rechnungsdatums von vorausgeganenen Rechnungen nicht als _30.09.2016_, sondern als _2016-09-30 [D].[M].[Y]_ ausgegeben.
![OXT1](https://user-images.githubusercontent.com/75128473/100456185-3ec6c480-30c0-11eb-9747-d9b69cd3c797.png)
[XRechnung.xml.txt](https://github.com/jcthiele/OpenXRechnungToolbox/files/5608120/XRechnung.xml.txt)

**Comment by jcthiele** [comment]
Moin hiwilfried,

OXT stellt weder eine eigene Visualisierung- noch eine eigene Validierungsroutine bereit. Es ist lediglich eine Benutzeroberfläche für die von der KoSIT als Betreiberin des Standards XRechnung bereitgestellten Tools. 
Insofern hat OXT auch keinen Einfluss auf die Darstellung von Datumsangaben. 
Daher bitte solche Issues an die KoSIT melden (https://github.com/itplr-kosit/xrechnung-visualization) oder mir einen Hinweis geben, falls es bereits ein neues Release gibt, welche ich verpasst haben sollte in OXT einzubauen.
Besten Dank und viele Grüße
Jan Thiele
