### ISSUE TITLE
Kein einheitliches Konzept für Betreff einer Bemerkung zur Rechnung

### ISSUE THREAD

**Issue by hiwilfried** [jcthiele/OpenXRechnungToolbox#2]
Der Betreff einer Rechnungsbemerkung wird von der OXT nicht ausgewertet. Zugrunde gelegt wird die Art und Weise, in der der Betreff in Form einer 3-Buchstaben-Kombination von Dataport [in der Weberfassung](https://onlinedienste.bremen.de/Onlinedienste/FVS/FV/Dataport/ERechnung/Home) in das UBL-Invoice-XML-Format übersetzt wird, nämlich abgetrennt durch ein Doppelkreuz hinter der eigentlichen Bemerkung. 
Leider ist die Übersetzungsregel, mithilfe derer ein UBL-Invoice-XML auf Korrektheit hinsichtlich der XRechnungs-Spezifikation geprüft wird, an dieser Stelle sehr komplex aufgebaut:
```xml
<!--Manuell erstelltes Template für BG-1-->
<xsl:for-each-group select="./cbc:Note" group-by="             if (following-sibling::cbc:Note and matches(., '^[A-Z]{3}$')) then             generate-id(following-sibling::cbc:Note[1])             else             generate-id(.)">
	<xr:INVOICE_NOTE>
		<xsl:attribute name="xr:id" select="'BG-1'"/>
		<xsl:attribute name="xr:src" select="xr:src-path($current-bg)"/>
		<xsl:if test="count(current-group()) gt 1">
			<xr:Invoice_note_subject_code>
				<xsl:attribute name="xr:id" select="'BT-21'"/>
				<xsl:attribute name="xr:src" select="xr:src-path(current-group()[1])"/>
				<xsl:value-of select="current-group()[1]"/>
			</xr:Invoice_note_subject_code>
		</xsl:if>
		<xr:Invoice_note>
			<xsl:attribute name="xr:id" select="'BT-22'"/>
			<xsl:attribute name="xr:src" select="xr:src-path(current-group()[last()])"/>
			<xsl:value-of select="current-group()[last()]"/>
		</xr:Invoice_note>
	</xr:INVOICE_NOTE>
</xsl:for-each-group>
```
Klar ist: In UBL-Invoice-XML gibt es für Rechnungsbemerkungen nur **ein** (attributfreies) Element, die XRechnungs-Spezifikation indes sieht **zwei** Elemente vor. Die Übersetzungsregel scheint hier von Dataport von OXT unterschiedlich interpretiert zu werden, und einer von beiden muss ja falsch liegen. Ich vermute Dataport, da von einem Doppelkreuz in der Transformationsregel nicht die Rede ist.
Anbei ein Code-Beispiel direkt aus der Weberfassung heruntergeladen. Es wurde lediglich die veraltete <CustomizationID> 1.2 nach 2.0 korrigiert.
[eRechnung.xml.txt](https://github.com/jcthiele/OpenXRechnungToolbox/files/5614411/eRechnung.xml.txt)

**Comment by jcthiele** [comment]
Moin hiwilfried,

hier hat die OXT selbst keinen Einfluss drauf. 
Für die Validierung wird der Validator der KoSIT genutzt (https://github.com/itplr-kosit/validator) mit entsprechender Konfiguration für XRechnung, welche ebenfalls von der KoSIT bereitgestellt wird (https://github.com/itplr-kosit/validator-configuration-xrechnung). Für die Visualisierung kommen die Visualisierungs-Komponenten der KoSIT bzw. des KKR zum Einsatz (https://github.com/itplr-kosit/xrechnung-visualization). Hier findet lediglich eine Anreicherung bzgl. der Codelisten-Auflösung statt (https://github.com/jcthiele/xrechnung-visualization-codelist-resolve). Ansonsten erfolgt keine Modifikation. Insofern sind entsprechende Issues dort bei der Quelle zu prüfen/zu melden.
Bei Issues an der Dataport-Implementierung bitte diese dorthin melden (dataporthilfee-rechnung@dataport.de). 
Das einzige, was passieren kann, ist, dass ich mit den Releases in OXT mal hinter den Releases der KoSIT hinterherhänge. Dann gern einen Hinweis geben. 

Besten Dank und viele Grüße
Jan Thiele
