### ISSUE TITLE
Erkannter Dokumenttyp "Unbekannt" bei Verwendung der Beispieldaten

### ISSUE THREAD

**Issue by dvr-ds** [jcthiele/OpenXRechnungToolbox#3]
Hallo Herr Thiele,

wir haben eine XRechnung in der Version 1.2 erhalten, für die der Prüfbericht ein Zurückweisen der Rechnung empfohlen hat, weil der erkannte Dokumenttyp "unbekannt" ist. Dasselbe Ergebnis zeigt sich auch bei den im Programm mitgelieferten Beispieldaten der Version 1.2 (ich glaube sogar, alle außer 2.0).
![grafik](https://user-images.githubusercontent.com/75412221/100972222-b4a3b380-3538-11eb-830c-e18be8e8ff4f.png)

Handelt es sich dabei um einen fehlerhaften Prüfbericht? Können Sie das Problem ggf. fixen?

Vielen Dank!

Viele Grüße
DS

**Comment by jcthiele** [comment]
Hallo,

in den Einstellungen im Hauptfenster (zweiter Menüeintrag) wird das gewünschte Prüfszenario eingestellt. Ist dort 2.0 oder 1.2.2 ausgewählt?

Viele Grüße 
Jan Thiele

**Comment by dvr-ds** [comment]
Hallo Herr Thiele,

vielen Dank für die schnelle Antwort. Dort ist 2.0.0 eingestellt. Beim Versuch auf 1.2.0 umzustellen erscheint die folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/75412221/100973328-a6569700-353a-11eb-849a-4015b51b2808.png)

Viele Grüße
DS

**Comment by dvr-ds** [comment]
Hallo Herr Thiele,

die Einstellung wurde trotz der Fehlermeldung geändert. Die Prüfung ist mit der neuen Einstellung erfolgreich gewesen.

Es wäre sehr praktisch, wenn die User nicht die Version der XRechnung herausfinden müssten, um die Prüfung erfolgreich durchzuführen.

Besteht die Möglichkeit, das Tool so anzupassen, dass es die Version automatisch bestimmt und das entsprechende Prüfszenario anwendet?

Vielen Dank!

Viele Grüße
DS

**Comment by jcthiele** [comment]
Hallo,

der angezeigte Fehler klingt nach fehlenden Schreibrechten im verwendeten Verzeichnis. Verwunderlich, dass es trotzdem geklappt hat.

Die Prüfszenarien zu kombinieren geht grundsätzlich. Ich könnte so eine Szenariodatei anbieten. Allerdings hatte ich mich zunächst bewußt dagegen entschieden, da es üblicherweise ein Zielszenario gibt, gegen das zu prüfen ist, da auch nur jeweils eine XRechnungsversion zu einem Zeitpunkt gültig ist. Insofern fürchte ich, dass am Ende die Verwirrung noch größer ist, wenn der Prüfbericht Validität ausweist, aber die 'falsche' Version genutzt wurde. Ich überlege aber nochmal, ob ich in einem zukünftigen Release zumindest zusätzlich auch noch eine kombinierte Szenariodatei anbiete.

Viele Grüße 
Jan Thiele

**Comment by dvr-ds** [comment]
Hallo Herr Thiele,

vielen Dank für die schnelle Klärung!

Viele Grüße
DS
