### ISSUE TITLE
Neue Version XRechnung 2.3.1

### ISSUE THREAD

**Issue by 00500500** [jcthiele/OpenXRechnungToolbox#5]
Hallo,

es wurde eine neue Version des XRechnungsstandards veröffentlich, welche geplant am 01.08.2023 live gehen soll.
Es würde uns freuen, wenn Sie die Toolbox um diese Version erweitern.
[https://xeinkauf.de/xrechnung/](https://xeinkauf.de/xrechnung/)

Danke

**Comment by FRG-XR** [comment]
Guten Tag,

möchte mich dem Vorposter anschließen und um eine Aktualisierung bitten.
Dieses Tool hat uns schon eine Menge Zeit gespart und wir sind Ihnen für Ihre Arbeit sehr dankbar!

XRechnung 2.3.1   ->   12.05.2023 (Gültig ab 01.08.2023)
XRechnung 3.0.0   ->   28.07.2023 (Gültig ab 01.02.2024)

MfG

**Comment by jcthiele** [comment]
Update auf OpenXRechnungsToolbox enthält Support bis XRechnung 3.0.2.
