### ISSUE TITLE
Abrechnungszeitraum wird nicht visualisiert

### ISSUE THREAD

**Issue by BOS1337** [jcthiele/OpenXRechnungToolbox#6]
Der Abrechnungszeitraum auf Kopfeben wird nicht visualisiert

InvoicePeriod
	StartDate
	EndDate

**Comment by jcthiele** [comment]
Die OpenXRechnungToolbox nutzt die von der KoSIT bereitgestellte Visualisierungskomponente. Bugfixes finden dort statt und können dann in die OpenXRechnungToolbox übernommen werden. 
Die benannten Fehler sollte mit der Version 3.0.0 behoben sein.
