### ISSUE TITLE
ZUGFeRD support

### ISSUE THREAD

**Issue by Amerlander** [jcthiele/OpenXRechnungToolbox#7]
Could it be possible to add support for ZUGFeRD files?

https://www.mustangproject.org/zugferd/

**Comment by jcthiele** [comment]
ZUGFeRD is already supported by the OpenXRechnungToolbox.
You can validate, visualize and convert ZUGFeRD invoices of Profile XRechnung (xml). 
(Tested with ZUGFeRD 2.3 and OpenXRechnungToolbox 3.0.0 with validation profile XRechnung 3.0.2)
For the other Profiles of ZUGFeRD there is no need for visualization as they are hybrid invoices. 
Furthermore, there are other projects supporting hybrid invoice formats.
The OpenXRechnungToolbox is for digital, structured invoices only.

**Comment by Amerlander** [comment]
It was more for beeing able to check if the XML part in a PDF is the same as the visual part.

I tried to create ZUGFeRD files in Fakturama, but it did not seemed to work. And I had trouble to check the XML part and it would have been nice, if I could just use one tool for all these xRechnung checks.

**Comment by jcthiele** [comment]
If the XML is in XRechnung Profile you are able to visualize the xml-part with OpenXRechnungToolbox v3.0.0 (just released). Just export the xml from the pdf. However, your scenario shows nicely why hybrid formats are not always a good idea as they sometimes produce more problems than they solve.
