### ISSUE TITLE
Aktuelle Signaturen für Windows Installer

### ISSUE THREAD

**Issue by gbischmi** [jcthiele/OpenXRechnungToolbox#8]
Die Ausführungsverhinderung greift unter Windows für die im Jahr 2022 bereitgestellten Installer-Pakete.

Bitte mal aktuelle Signaturen anfügen.

**Comment by jcthiele** [comment]
Das hat nichts mit nicht-aktuellen Signaturen zu tun, sondern damit, dass die Signatur selbst ausgestellt und nicht von einer offiziellen CA ausgegeben wurde. Wenn jemand die Kosten für die Signatur übernehmen möchte, gern...
Ansonsten gilt: im Microsoft Defender auf "Weitere Informationen" > "Trotzdem ausführen" klicken. 
Alternativ anstelle des Installers das Windows-zip-Paket herunterladen, entpacken und die .exe-Datei per Doppelklick ausführen.  
Daran stört sich der Microsoft Defender nicht (zumindest bei meinen Tests).
