### ISSUE TITLE
MacOS Apple Silicon Support

### ISSUE THREAD

**Issue by gapthorpe** [jcthiele/OpenXRechnungToolbox#9]
Hi
I have attempted to run this on MacOS (Apple Silicon), and get errors such as:
.swt/lib/macosx/aarch64/libswt-cocoa-4626.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))

Can this support arm64?

Many thanks!

**Comment by jcthiele** [comment]
Hi,
sorry, I don't have an Apple machine, therefore I'm not able to test the releases on MacOS.
The swt-library is known as problemmatic. Therefore, with an older release I created a solution together with a Mac-user. 
However, I don't know if it is still working.
Have you started the toolbox with the start script for Mac (OpenXRechnungToolboxMac.sh)? 
Is an apropriate Java installed? 
I will release a new version 3.0.0 for Java >=9, soon. You could test this.
However, as mentioned above, further support isn't possible for me, as I'm not a Mac user.

Kind regards.

**Comment by gapthorpe** [comment]
Thanks for getting back to me so quickly and no problem, completely understand.  That is great a new version is coming, will test this once available and will let you know.
